### ISSUE TITLE
message: "StatusCodeError", statusCode: 429 when 10 translation occoured

### ISSUE THREAD

**Issue by skchowdhury** [FreddieDeWitt/google-translate-extended-api#4]
Hello
I am using your extended-google-tranlate-api.It's working fine but after some time suppose after 10 translation a time within 1 min it give message: "StatusCodeError", statusCode: 429.
so please tell me how to solve this issue

**Comment by FreddieDeWitt** [comment]
This happens when you make to many requests per minute. I would suggest lowering the number of requests.
