### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by parsalotfy** [FreddieDeWitt/google-translate-extended-api#6]
Hi,
I'm a c# programmer,
I don't know enough about json and nodejs and these bunch of web stuff.
I saw [this tutorial in youtube](https://www.youtube.com/watch?v=8Rmj5UY5mJk&ab_channel=iEatWebsites) and it used Browserify to bundle main.js.
I did it , but there is an error :
![image](https://user-images.githubusercontent.com/30390810/93819657-dd6e1980-fc68-11ea-8b27-6ccbd654dc8d.png)

This is what I exactly did :

1) create html page
2) create js file
3) refrence the js file in html page
4) run :  `npm init`
5) run : `npm i extended-google-translate-api`
6) run : `browserify main.js -o bundle.js`

and that error happens.
Could you please tell me what should I do ?
Thank you.
Parsa Lotfi

**Comment by FreddieDeWitt** [comment]
Unfortunately, I have never needed to use JS from C#, so I'm afraid I can't help you with this.
