### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Redstone-Hamster** [FreddieDeWitt/google-translate-extended-api#7]
![image](https://user-images.githubusercontent.com/53989469/102848272-0c1b9d80-43da-11eb-96e1-228aa046522b.png)
I get this error every time I use this.

**Comment by kof** [comment]
can confirm

**Comment by tsdmrfth** [comment]
+1

**Comment by iieternal** [comment]
Any work arounds

**Comment by FreddieDeWitt** [comment]
Hi! Yeah, unfortunately, google has changed the way you need to send and process the request, therefore it wasn't working. Luckily, the creator of @vitalets/google-translate-api was able to find a workaround for this, so I have updated the repository and it should work fine now.
